---
- name: ensure .ssh directory exists.
  file:
    dest: ~/.ssh
    mode: 0700
    state: directory

- name: install ssh config
  copy:
    src: vault/ssh_config
    dest: ~/.ssh/config
    mode: 0600

- name: install ssh key
  copy:
    src: vault/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: install ssh public key
  copy:
    src: vault/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: 0600

- name: use ssh keys for identity
  lineinfile:
    dest: ~/.ssh/config
    line: IdentityFile ~/.ssh/id_rsa

- name: Ensure .gnupg directory exists.
  file:
    dest: ~/.gnupg
    mode: 0700
    state: directory

- name: Install gpg configs
  copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    mode: 0600
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Receive personal public key
  shell: "/usr/bin/gpg2 --recv {{ pgp_key_id }}"
