---
- name: ensure .ssh directory exists.
  file:
    dest: "~/.ssh"
    mode: 0700
    owner: pbovbel
    state: directory

- name: install ssh config
  copy:
    src: ssh_config
    dest: ~/.ssh/config
    mode: 0600
    owner: pbovbel

- name: define ssh keys
  set_fact:
    ssh_keys:
      - id_rsa
      - id_locus
      - id_clearpath

- name: install ssh key
  copy:
    src: "vault/{{ item }}"
    dest: "~/.ssh/{{ item }}"
    mode: 0600
    owner: pbovbel
  with_items: "{{ ssh_keys }}"

- name: install ssh public key
  copy:
    src: "vault/{{ item }}.pub"
    dest: "~/.ssh/{{ item }}.pub"
    mode: 0600
    owner: pbovbel
  with_items: "{{ ssh_keys }}"

- name: use ssh keys for identity
  lineinfile:
    dest: ~/.ssh/config
    line: "IdentityFile ~/.ssh/{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: Ensure .ssh directory exists.
  file:
    dest: "~/.gnupg"
    mode: 0700
    owner: pbovbel
    state: directory

- name: Install gpg rings
  copy:
    src: "vault/{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    mode: 0600
    owner: pbovbel
  with_items:
    - pubring.gpg
    - secring.gpg
    - trustdb.gpg
