---
- name: install jupyter dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  with_items:
    - ipython
    - ipython-notebook

- name: install/upgrade pip
  pip:
    name: pip
    state: latest
  become: true

- name: install jupyter
  pip:
    name: jupyter
    state: latest
  become: true

- name: install python3 kernel
  pip:
    name: ipykernel
    state: latest
    executable: pip3
  become: true

- name: configure python3 kernel
  shell: |
    python3 -m ipykernel install
  become: true

- name: ensure ~/jupyter directory exists.
  file:
    dest: ~/jupyter
    state: directory

- name: install jupyter service
  template:
    src: jupyter.service.j2
    dest: ~/.config/systemd/user/jupyter.service

- name: enable jupyter service
  systemd:
    name: jupyter.service
    state: started
    enabled: true
    daemon_reload: true
    user: true
