---
- name: add flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items: "{{ flatpak_install }}"

- name: create user systemd dir
  file:
    path: ~/.config/systemd/user
    state: directory

- name: setup flatpak update timer
  copy:
    content: |
      [Unit]
      Description=Flatpak update

      [Timer]
      OnCalendar=7:00
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: ~/.config/systemd/user/flatpak-update.timer
  notify: enable flatpak update

- name: setup flatpak update service
  copy:
    content: |
      [Unit]
      Description=Flatpak update

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/flatpak update -y
    dest: ~/.config/systemd/user/flatpak-update.service
  notify: enable flatpak update
