---
- name: add flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpak_install }}"
  become: true

- name: setup flatpak update timer
  copy:
    content: |
      [Unit]
      Description=Flatpak update

      [Timer]
      OnCalendar=7:00
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/flatpak-update.timer
  become: true
  notify: enable flatpak update

- name: setup flatpak update service
  copy:
    content: |
      [Unit]
      Description=Flatpak update

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/flatpak --system update -y
    dest: /etc/systemd/system/flatpak-update.service
  become: true
  notify: enable flatpak update

# TODO(pbovbel) set flatpak dark theme
