plex_claim: ""

docker:
  services:
    mariadb:
      image: mariadb
      container_name: mariadb
      networks:
        - apps
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      restart: "no"
      volumes:
        - "{{ app_folder }}/nextcloud/db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=asdf
        - MYSQL_PASSWORD=qwerty
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud

    redis:
      image: redis:alpine
      container_name: redis
      restart: "no"
      networks:
        - apps

    nextcloud:
      image: nextcloud:apache
      container_name: nextcloud
      restart: "no"
      networks:
        - apps
      volumes:
        - "{{ app_folder }}/nextcloud/app:/var/www/html"
      environment:
        # - MYSQL_HOST=mariadb
        - REDIS_HOST=redis
        # - MYSQL_PASSWORD=qwerty
        # - MYSQL_DATABASE=nextcloud
        # - MYSQL_USER=nextcloud
        - TRUSTED_PROXIES=caddy
      # x-systemd-requires:
      #   - docker-mariadb.service
      #   - docker-redis.service

    cron:
      image: nextcloud:apache
      container_name: cron
      restart: "no"
      networks:
        - apps
      volumes:
        - "{{ app_folder }}/nextcloud/app:/var/www/html"
      entrypoint: /cron.sh



caddy:
  remotes:
    cloud:
      host: nextcloud
      domain: bovbel.com
      auth: oauth
      roles: ['admin', 'cloud']
