---
- name: restart caddy
  service:
    name: caddy
    state: restarted
  become: true

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: true

- name: configure caddy
  include_tasks: handlers/configure-caddy.yaml
