---
- name: install cockpit packages
  apt:
    name:
      - cockpit
      - cockpit-bridge
      - cockpit-packagekit
      - cockpit-pcp
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
    default_release: "{{ ansible_distribution_release }}-backports"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: cockpit

- name: configure cockpit
  template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
  become: true
  notify: restart cockpit

- name: make sure cockpit is running
  service:
    name: cockpit
    state: started
    enabled: true
  become: true

- name: configure cockpit caddy
  set_fact:
    caddy: "{{ caddy | combine(caddy_cockpit, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure caddy
  tags: caddy

- name: configure cockpit docker
  set_fact:
    containers: "{{ containers | combine(container_cockpit, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure containers
  tags: containers
