---
- name: install cockpit packages
  apt:
    name:
    - cockpit
    - cockpit-bridge
    - cockpit-dashboard
    - cockpit-packagekit
    - cockpit-pcp
    - cockpit-storaged
    - cockpit-system
    - cockpit-ws
    default_release: "{{ ansible_distribution_release }}-backports"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: configure cockpit
  template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
  become: true
  notify: restart cockpit

- name: make sure cockpit is running
  service:
    name: cockpit
    state: started
    enabled: true
  become: true
