---
- name: setup atom as default editor
  lineinfile:
    dest: /usr/share/applications/defaults.list
    line: "{{ item }}=atom.desktop"
    regexp: "^{{ item.0 }}=.*"
  with_items:
    - application/x-perl
    - text/mathml
    - text/plain
    - text/x-c++hdr
    - text/x-c++src
    - text/x-chdr
    - text/x-csrc
    - text/x-dtd
    - text/x-java
    - text/x-python
    - text/x-sql
    - text/xml
  become: true
  tags:
    - desktop

- name: Install atom apt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  with_items:
    - python-pip
    - cppcheck

- name: Install atom pip packages
  pip:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - cpplint
    - flake8
    - pep8

- name: Configure atom modules
  command: /usr/bin/apm install {{ item }} --production
  with_items:
    - atom-beautify
    - auto-detect-indentation
    - file-types
    - git-blame
    - language-cmake
    - language-markdown
    - linter
    - linter-cppcheck
    - linter-cpplint
    - linter-flake8
    - linter-markdown
    - linter-python-pep8
    - markdown-preview-plus
    - markdown-writer
    - merge-conflicts
    - minimap
    - project-manager
    - sort-lines
  args:
    creates: ~/.atom/packages/{{ item }}/
  tags:
    - desktop
