apt_remove:
  - packages: []

apt_install:
  - packages: []
    repo: "deb http://archive.canonical.com/ubuntu/ {{ ansible_distribution_release }} partner"
    filename: /etc/apt/sources.list

  - packages: 
    # for dev
    - openssh-server
    - openssh-client
    - ubuntu-restricted-extras
    - ubuntu-restricted-extras
    - va-driver-all
    - vainfo
    - libva2
    - gstreamer1.0-libav
    - gstreamer1.0-vaapi
    - swapspace
    - iperf
    - htop
    - ipython3
    - vlc
    - solaar-gnome3

  - packages: 
    # for yubikey
    - pcscd
    - scdaemon
    - gnupg2
    - pcsc-tools

  - packages: ['unetbootin']
    repo: ppa:gezakovacs/ppa
    filename: unetbootin

  - packages: ['numix-*']
    repo: ppa:numix/ppa
    filename: numix

  - packages: ['wireshark']
    repo: ppa:wireshark-dev/stable
    filename: wireshark

  - packages: ['remmina']
    repo: ppa:remmina-ppa-team/remmina-next
    filename: remmina

  - packages: ['resilio-sync']
    repo: "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free"
    keyurl: https://linux-packages.resilio.com/resilio-sync/key.asc
    filename: resilio

  - packages: ['code']
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    keyurl: https://packages.microsoft.com/keys/microsoft.asc
    filename: code

  - packages: ['terminator']

  - packages: ['chrome-gnome-shell', 'libproxy1-plugin-networkmanager', 'gnome-shell-extension-system-monitor']

  - packages: ['gnome-tweak-tool']

  - packages: ['flatpak']

flatpak_install:
  - com.slack.Slack
  - com.spotify.Client
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.signal.Signal
  - us.zoom.Zoom

vscode:
  extensions:
    - akamud.vscode-theme-onedark
