
docker_caddy:
  services:
    caddy:
      # TODO(pbovbel): build a caddy image containing jwt and auth_portal on demand
      image: paulbovbel/caddy:2.2.1
      container_name: caddy
      networks:
        - apps
      ports:
        - 80:80
        - 443:443
      restart: "no"
      volumes:
        - /etc/docker/Caddyfile:/etc/caddy/Caddyfile:ro
        - "{{ app_folder }}/caddy/data:/data"
        - "{{ app_folder }}/caddy/config:/config"
        - "{{ share_folder }}:/share:ro"
      environment:
        - "TZ=America/Toronto"  # TODO(pbovbel) not working https://github.com/caddyserver/caddy-docker/issues/58

caddy: {}

caddy_defaults:
  users: []
  endpoints:
    share:
      type: share
      auth: oauth
      path: /share
      roles:
        - share
  remotes: {}
  token_secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') | to_uuid }}"

# TODO(pbovbel)
# caddy_version: 2.2.1
# caddy_plugins:
#   - github.com/greenpau/caddy-auth-portal@v1.2.19
#   - github.com/greenpau/caddy-auth-jwt@v1.1.9
