---
caddy_version: 2.6.4
caddy_plugins:
  - github.com/greenpau/caddy-security@v1.1.18

docker_caddy:
  services:
    caddy:
      build:
        context: /etc/caddy/
      container_name: caddy
      networks:
        - apps
      ports:
        - 80:80
        - 443:443
      restart: "no"
      volumes:
        - /etc/caddy:/etc/caddy:ro
        - "{{ app_folder }}/caddy/data:/data"
        - "{{ app_folder }}/caddy/config:/config"
        - "{{ share_folder }}:/share:ro"
      environment:
        TZ: America/Toronto  # TODO(pbovbel) not working https://github.com/caddyserver/caddy-docker/issues/58
    filebrowser:
      image: filebrowser/filebrowser
      container_name: filebrowser
      networks:
        - apps
      volumes:
        - "{{ share_folder }}:/srv"
        - "{{ app_folder }}/filebrowser/filebrowser.db:/database.db"
      command: "-b /browser"

caddy: {}

caddy_defaults:
  users: []
  endpoints:
    share:
      type: share
      auth: oauth
      path: /share
      roles: ['share']
    browser:
      type: proxy
      auth: oauth
      path: /browser
      host: filebrowser
      port: 80
      roles: ['admin']
  token_secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') | to_uuid }}"
