---
- name: install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: configure caddy fail2ban filter
  copy:
    dest: '/etc/fail2ban/filter.d/caddy-basic-auth.conf'
    content: |
      # fail2ban filter configuration for caddy basicauth
      [Definition]
      failregex = ^.*error.*remote_addr": "<HOST>.*"Authorization": \["Basic.*"status": (400|401).*$
      ignoreregex =
  become: true
  notify: restart fail2ban

- name: configure caddy fail2ban jail
  blockinfile:
    marker: "# {mark} include caddy fail2ban config"
    path: '/etc/fail2ban/jail.local'
    block: |
      [caddy-basic-auth]
      enabled  = true
      chain    = DOCKER-USER
      port     = http,https
      logpath  = {{ app_folder }}/caddy/data/log/error.log
    state: present
    create: true
  become: true
  notify: restart fail2ban

- name: configure caddy defaults
  set_fact:
    caddy: "{{ caddy | combine(caddy_defaults, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure caddy
  tags: caddy

- name: configure caddy docker
  set_fact:
    docker: "{{ docker | combine(docker_caddy, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure docker
  tags: docker
