cleanup_downloads_age: 120

docker_media_server:
  services:
    plex:
      image: plexinc/pms-docker:plexpass
      container_name: plex
      networks:
        - apps
      ports:
        - 32400:32400
      volumes:
        - "{{ app_folder }}/plex:/config"
      tmpfs:
        - "/transcode"
      environment:
        PLEX_UID: "{{ ansible_user_uid }}"
        PLEX_GID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
        ADVERTISE_IP: "http://{{ ansible_default_ipv4.address }}:32400/"
      devices:
        - /dev/dri:/dev/dri
      restart: "no"
    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      networks:
        - apps
      depends_on:
        - plex
      volumes:
        - "{{ app_folder }}/tautulli:/config"
        - "{{ app_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      restart: "no"
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
    sonarr:
      image: linuxserver/sonarr:latest
      container_name: sonarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "{{ app_folder }}/sonarr:/config"
        - "{{ tv_folder }}:/tv"
        - "{{ downloads_folder }}:/downloads"
      restart: "no"
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - "{{ app_folder }}/radarr:/config"
        - "{{ movies_folder }}:/movies"
        - "{{ downloads_folder }}:/downloads"
      restart: "no"
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
        TZ: America/Toronto
    readarr:
      image: linuxserver/readarr:nightly
      container_name: readarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - "{{ app_folder }}/readarr:/config"
        - "{{ downloads_folder }}:/downloads"
        - "{{ books_folder }}:/books"
        - "{{ audiobooks_folder }}:/audiobooks"
      restart: "no"
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
    bazarr:
      container_name: bazarr
      image: linuxserver/bazarr
      networks:
        - apps
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/bazarr:/config"
        - "{{ tv_folder }}:/tv"
        - "{{ movies_folder }}:/movies"
      restart: "no"
    mylar3:
      image: linuxserver/mylar3
      container_name: mylar3
      networks:
        - apps
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/mylar3:/config"
        - "{{ comics_folder }}:/comics"
        - "{{ downloads_folder }}:/downloads"
      ports:
        - 8090:8090
      restart: unless-stopped
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      networks:
        - apps
      volumes:
        - "{{ app_folder }}/jackett:/config"
      restart: "no"
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
    deluge:
      container_name: deluge
      image: binhex/arch-delugevpn
      privileged: true
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      cap_add:
        - NET_ADMIN
      networks:
        - apps
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "{{ app_folder }}/deluge:/config"
        - "{{ downloads_folder }}:/downloads"
      ports:
        - 58846:58846
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
        STRICT_PORT_FORWARD: "yes"
        LAN_NETWORK: "{{ lan_network }}"
        NAME_SERVERS: "8.8.8.8,8.8.4.4"
        DELUGE_DAEMON_LOG_LEVEL: info
        DELUGE_WEB_LOG_LEVEL: info
        DELUGE_ENABLE_WEBUI_PASSWORD: "no"
        VPN_ENABLED: "no"
    flaresolverr:
      container_name: flaresolverr
      image: flaresolverr/flaresolverr:latest
      networks:
        - apps
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
        CAPTCHA_SOLVER: 'none'
      restart: "no"

upnp_forwards_media_server:
  plex: {from: 32400, to: 32400, proto: tcp}

caddy_media_server:
  endpoints:
    radarr:
      type: proxy
      auth: oauth
      role: admin
      path: /radarr
      host: radarr
      port: 7878

    readarr:
      type: proxy
      auth: oauth
      role: admin
      path: /readarr
      host: readarr
      port: 8787

    sonarr:
      type: proxy
      auth: oauth
      role: admin
      path: /sonarr
      host: sonarr
      port: 8989

    bazarr:
      type: proxy
      auth: oauth
      role: admin
      path: /bazarr
      host: bazarr
      port: 6767

    readarr:
      type: proxy
      auth: oauth
      role: admin
      path: /readarr
      host: readarr
      port: 8787

    mylar3:
      type: proxy
      auth: oauth
      role: admin
      path: /mylar
      host: mylar3
      port: 8090

    tautulli:
      type: proxy
      auth: oauth
      role: admin
      path: /tautulli
      host: tautulli
      port: 8181

    jackett:
      type: proxy
      auth: oauth
      role: admin
      path: /jackett
      host: jackett
      port: 9117

    deluge:
      type: proxy
      auth: oauth
      role: admin
      path: /deluge
      host: deluge
      port: 8112
      strip_prefix: true
      header_up:
        - X-Deluge-Base "/deluge"

    deluge-basic:
      type: proxy
      auth: basic
      user: "{{ web_user }}"
      password: "{{ web_password }}"
      path: /deluge-basic
      host: deluge
      port: 8112
      strip_prefix: true
      header_up:
        - X-Deluge-Base "/deluge-basic"

mam_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33393633653832666234303266613033343738346637653932313337353638396138373238623930
  3364336433383066616337333035373539653662373534310a303366383339653138373566346132
  33316636363335313739386531353763306537323562323036343731633235646565636338656439
  3566656235623234660a613463396365643138313132626630666133343530303334656232613639
  62663737336262653361363837613136316236363164333232383033393236623962303338313565
  36326239656434643633656666346361343163663464363635393432643530623964376332653762
  34383034646137366632613132326537643137383465326461326634346438626638336631393635
  64366436613532663737653832653866333930373631363730376532346430313832643030333835
  33646233313632653730376161376433663736323834623336653437393731653039373830346663
  64336230333764643364383233613831656666343330643332343935386133306437313365616362
  33373262346334386232663864383038633539653135346465363166376634323663333635393931
  33316563643836656665333466333633643437653365633634623032323965303662303836326131
  32663461303331646231393732346637376435643464643733336162636135363664313562626265
  65343639343336326537653133316438393433306465323234666465323239343663353661393734
  63376439383264373337303864336433656233316537303635353265356435303263356433383132
  36653763333335383761393533396535613932623931313634343130653635626662373661353132
  38663536343130663935623331326466316565613831386134663135373533383333643737323061
  37646265336262336237643565616439373135333234343535366639383734313865333461313239
  323965313565343763353038346236353635
