plex_claim: ""

docker_compose:
  services:
    plex:
      image: plexinc/pms-docker:plexpass
      container_name: plex
      networks:
        - apps
      ports:
        - 32400:32400
      volumes:
        - "{{ app_folder }}/plex:/config"
        - "{{ movies_folder }}:/data/movies:ro"
        - "{{ tv_folder }}:/data/tv:ro"
        - "{{ music_folder }}:/data/music:ro"
      tmpfs:
        - "/transcode"
      environment:
        - "PLEX_UID={{ uid }}"
        - "PLEX_GID={{ gid }}"
        - "TZ=America/Toronto"
        - "PLEX_CLAIM={{ plex_claim }}"
        - ADVERTISE_IP=http://{{ ansible_default_ipv4.address }}:32400/
      devices:
        - /dev/dri:/dev/dri
      restart: "no"
    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      networks:
        - apps
      depends_on:
        - plex
      volumes:
        - "{{ app_folder }}/tautulli:/config"
        - "{{ app_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      restart: "no"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "{{ app_folder }}/sonarr:/config"
        - "{{ tv_folder }}:/tv"
        - "{{ download_folder }}:/downloads"
      restart: "no"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - "{{ app_folder }}/radarr:/config"
        - "{{ movies_folder }}:/movies"
        - "{{ download_folder }}:/downloads"
      restart: "no"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      networks:
        - apps
      volumes:
        - "{{ app_folder }}/jackett:/config"
      restart: "no"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    transmission:
      container_name: transmission
      image: linuxserver/transmission:latest
      networks:
        - apps
      ports:
        - 51413:51413
      restart: "no"
      volumes:
        - "{{ app_folder }}/transmission:/config"
        - "{{ download_folder }}:/downloads"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"

caddy:
  endpoints:
    radarr:
      type: proxy
      auth: oauth
      path: /radarr
      host: radarr
      port: 7878
      users: "{{ admin_users }}"

    sonarr:
      type: proxy
      auth: oauth
      path: /sonarr
      host: sonarr
      port: 8989
      users: "{{ admin_users }}"

    tautulli:
      type: proxy
      auth: oauth
      path: /tautulli
      host: tautulli
      port: 8181
      users: "{{ admin_users }}"

    jackett:
      type: proxy
      auth: oauth
      path: /jackett
      host: jackett
      port: 9117
      users: "{{ admin_users }}"

    transmission:
      type: proxy
      auth: basic
      user: "{{ web_user }}"
      password: "{{ web_password }}"
      path: /transmission
      host: transmission
      port: 9091
