---
- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: true

- name: restart smartd
  service:
    name: smartd
    state: restarted
  become: true

- name: update-grub
  shell: update-grub
  become: true
