---
- name: install hwe
  apt:
    name: "linux-generic-hwe-{{ ansible_distribution_version }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: install zfs
  apt:
    name:
      - zfsutils-linux
      - zfs-auto-snapshot
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: zfs_pool is defined

- name: import pool if necessary
  shell: |
    zpool import {{ zfs_pool }} || true
  become: true
  when: zfs_pool is defined

- name: populate kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel_options | join(" ") }}"'
  become: true
  notify:
    - update-grub

- name: set timezone
  timezone:
    name: America/Toronto
  become: true
