---
docker_cockpit:
  services:
    smokeping:
      image: ghcr.io/linuxserver/smokeping
      container_name: smokeping
      networks:
        - apps
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/smokeping/config:/config"
        - "{{ app_folder }}/smokeping/data:/data"
      restart: unless-stopped

caddy_cockpit:
  redirect: /dashboard/

  endpoints:
    smokeping:
      type: proxy
      auth: oauth
      path: /smokeping
      host: smokeping
      port: 80
      role: admin

    cockpit:
      type: proxy
      auth: oauth
      # bypass internal login by passing down basic auth headers
      spoof_basic: true
      path: /cockpit
      host: "{{ ansible_default_ipv4.address }}"
      port: 9090
      role: admin

plugin_docker_version: v2.0.3
plugin_zfs_version: e4b4496d63260466045260a924d5d456aaf10bda
