---
aws_alias_domains:
  - octopi.bovbel.com
  - tower.bovbel.com
  - pihole.bovbel.com

# Useful paths
data_folder: "/home/{{ ansible_user }}"
app_folder: "{{ data_folder }}/app"
share_folder: "{{ data_folder }}/share"

docker_extras:
  services:
    unifi:
      image: linuxserver/unifi-controller
      container_name: unifi
      network_mode: host
      volumes:
        - "{{ app_folder }}/unifi:/config"
      restart: "no"
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto

caddy_extras:
  users:
    - name: paul@bovbel.com
      roles: ['admin', 'share']
