---
pia_username: p4418147
pia_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38383866646163623333386539326666363939323938643761396463343135303533346530663234
  3463326135353933613238323432303730653433336263620a363762333739633330363230376139
  33643133623438353734303732666232663765306565306363303039306435653834663663313134
  6163316363393166340a643936393235383464313664613230636637353363666337653939366561
  6136

# Useful paths
data_folder: /mnt/storage
app_folder: "{{ data_folder }}/app"
media_folder: "{{ data_folder }}/media"
backup_folder: "{{ data_folder }}/backup"
downloads_folder: "{{ data_folder }}/downloads"
share_folder: "{{ media_folder }}"
movies_folder: "{{ media_folder }}/movies"
tv_folder: "{{ media_folder }}/tv"

zfs_pool: storage

media_server: true

aws_alias_domains:
  - minecraft.bovbel.com
  - cs.bovbel.com
  - valheim.bovbel.com

docker_extras:
  services:
    plex:
      volumes:
        - "{{ media_folder }}:/mnt/storage/share:ro"
      x-systemd-requires: ['mnt-storage.mount']
    deluge:
      environment:
        VPN_ENABLED: "yes"
        VPN_PROV: pia
        VPN_USER: "{{ pia_username }}"
        VPN_PASS: "{{ pia_password }}"
        VPN_CLIENT: wireguard
      x-systemd-start-post:
        # deluge thin client iptable rule to allow external access
        # https://github.com/binhex/arch-delugevpn/issues/139
        - "/sbin/iptables -t nat -A POSTROUTING -p tcp --dport 58846 -j SNAT --to-source {{ ansible_default_ipv4.address }}"
      x-systemd-requires: ['mnt-storage.mount']
    jellyfin:
      image: linuxserver/jellyfin
      container_name: jellyfin
      networks:
        - apps
      ports:
        - 8096:8096
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/jellyfin:/config"
        - "{{ media_folder }}:/data:ro"
      devices:
        - /dev/dri:/dev/dri
      restart: "no"
      x-systemd-requires: ['mnt-storage.mount']
    tautulli:
      x-systemd-requires: ['mnt-storage.mount']
    sonarr:
      x-systemd-requires: ['mnt-storage.mount']
    radarr:
      x-systemd-requires: ['mnt-storage.mount']
    jackett:
      x-systemd-requires: ['mnt-storage.mount']
    resilio:
      image: linuxserver/resilio-sync
      container_name: resilio
      networks:
        - apps
      ports:
        - 55555:55555
        - 55555:55555/udp
      volumes:
        - "{{ app_folder }}/resilio:/config"
        - "{{ data_folder }}:/sync"
      restart: "no"
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
      x-systemd-requires:
        - mnt-storage.mount
    minecraft:
      image: itzg/minecraft-server
      container_name: minecraft
      networks:
        - apps
      ports:
        - "25565:25565"
      volumes:
        - "{{ app_folder }}/minecraft:/data"
      environment:
        UID: "{{ uid }}"
        GID: "{{ gid }}"
        EULA: "TRUE"
        MAX_MEMORY: "16G"
        ENABLE_AUTOPAUSE: "TRUE"
        WHITELIST: "{{ minecraft_users | join(',') }}"
        OPS: "{{ minecraft_ops | join(',') }}"
        ENABLE_RCON: "TRUE"
        RCON_PASSWORD: "{{ web_password }}"
        TYPE: PAPER
      restart: "no"
      x-systemd-requires: ['mnt-storage.mount']
    csgo:
      image: kmallea/csgo
      container_name: csgo
      networks:
        - apps
      ports:
        - "27015:27015/tcp"
        - "27015:27015/udp"
        - "27020:27020/tcp"
        - "27020:27020/udp"
      volumes:
        - type: bind
          source: "{{ app_folder }}/csgo"
          target: /home/steam/csgo
      environment:
        SERVER_HOSTNAME: cs.bovbel.com
        SERVER_PASSWORD: "{{ csgo_server_password }}"
        RCON_PASSWORD: "{{ web_password }}"
        STEAM_ACCOUNT: "{{ csgo_app_id }}"
        SOURCEMOD_ADMINS: "{{ csgo_admins | join(',') }}"
      restart: "no"
      x-systemd-requires: ['mnt-storage.mount']
    # valheim:
    #   image: mbround18/valheim:latest
    #   container_name: valheim
    #   ports:
    #     - 2456:2456/udp
    #     - 2457:2457/udp
    #     - 2458:2458/udp
    #   environment:
    #     PUID: "{{ uid }}"
    #     PGID: "{{ gid }}"
    #     TZ: America/Toronto
    #     PORT: 2456
    #     NAME: "valheim.bovbel.com"
    #     WORLD: "World"
    #     PASSWORD: "{{ csgo_server_password }}"
    #     PUBLIC: 1
    #     AUTO_UPDATE: 1
    #     AUTO_UPDATE_SCHEDULE: "0 5 * * *"
    #     UPDATE_ON_STARTUP: 1
    #     AUTO_BACKUP: 1
    #     AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
    #     AUTO_BACKUP_REMOVE_OLD: 1
    #     AUTO_BACKUP_DAYS_TO_LIVE: 5
    #     AUTO_BACKUP_ON_UPDATE: 1
    #     AUTO_BACKUP_ON_SHUTDOWN: 1
    #   volumes:
    #     - "{{ app_folder }}/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim"
    #     - "{{ app_folder }}/valheim/server:/home/steam/valheim"
    #     - "{{ app_folder }}/valheim/backups:/home/steam/backups"
    #   restart: "no"
    #   x-systemd-requires: ['mnt-storage.mount']

csgo_server_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39623639626633623466376534303537613431653232613764343239386337386638626162313636
  3832613261326133393532306438306535643961373166300a613764616135333865393639393137
  61306666326435653231646634373162393238363162363863666563346233396431636131343435
  3166393736383761360a346232633439316564653433653230323536323535313665613134383564
  3832
csgo_app_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30666361353763396136666231383963613731333266386664386637313736383261383530343561
  6333383138393932383031646131656434646165393463370a636666386136353537386436633631
  39653735333636643231623139373038633831653266333630633266346633363732383134386665
  6330303661316666660a313934393039613833313166373738343961336530623031646637396365
  32353330373531626330663338636366353832373439643637343365343936376237363830316363
  3033353437636662633239636462323334393630396239646435

csgo_admins:
  - STEAM_0:0:33888781  # agentx3r
  - STEAM_0:0:8806779   # Supernatur4l

minecraft_ops:
  - agentx3r
  - LEVI00

minecraft_users:
  - _rusted_
  - agentx3r
  - FeelsKaleMan
  - landon0909
  - LEVI00
  - NovaNoot
  - rusnconcussion
  - sufferingtree11
  - SushiBeyblade85
  - ur_hot

caddy_extras:
  users:
    - name: paul@bovbel.com
      roles: ['admin', 'share']
    - name: rebecca@bovbel.com
      roles: ['admin', 'share']
    - name: andrew@bovbel.com
      roles: ['share']
    - name: igorlitvinov@gmail.com
      roles: ['share']
    - name: garyservin@gmail.com
      roles: ['share']
    - name: ablakey@gmail.com
      roles: ['share']
    - name: eugene.tkach@gmail.com
      roles: ['share']


  endpoints:
    jellyfin:
      type: proxy
      auth: null
      path: /jellyfin
      host: jellyfin
      port: 8096
      roles: ['admin']
    resilio:
      type: proxy
      auth: oauth
      path: /gui
      host: resilio
      port: 8888
      roles: ['admin']
