---
pia_username: p4418147
pia_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38383866646163623333386539326666363939323938643761396463343135303533346530663234
  3463326135353933613238323432303730653433336263620a363762333739633330363230376139
  33643133623438353734303732666232663765306565306363303039306435653834663663313134
  6163316363393166340a643936393235383464313664613230636637353363666337653939366561
  6136

# Useful paths
data_folder: /mnt/storage
app_folder: "{{ data_folder }}/app"
media_folder: "{{ data_folder }}/media"
backup_folder: "{{ data_folder }}/backup"
downloads_folder: "{{ data_folder }}/downloads"
share_folder: "{{ media_folder }}"
movies_folder: "{{ media_folder }}/movies"
tv_folder: "{{ media_folder }}/tv"

zfs_pool: storage

media_server: true

aws_alias_domains:
  - tower.bovbel.com

docker_extras:
  services:
    plex:
      volumes:
        - "{{ media_folder }}:/mnt/storage/share:ro"
      x-systemd-requires: ['mnt-storage.mount']
    unifi:
      image: linuxserver/unifi-controller
      container_name: unifi
      network_mode: host
      volumes:
        - "{{ app_folder }}/unifi:/config"
      restart: "no"
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
    deluge:
      environment:
        VPN_ENABLED: "yes"
        VPN_PROV: pia
        VPN_USER: "{{ pia_username }}"
        VPN_PASS: "{{ pia_password }}"
        VPN_CLIENT: wireguard
      x-systemd-start-post:
        # deluge thin client iptable rule to allow external access
        # https://github.com/binhex/arch-delugevpn/issues/139
        - "/sbin/iptables -t nat -A POSTROUTING -p tcp --dport 58846 -j SNAT --to-source {{ ansible_default_ipv4.address }}"
      x-systemd-requires: ['mnt-storage.mount']
    jellyfin:
      image: linuxserver/jellyfin
      container_name: jellyfin
      networks:
        - apps
      ports:
        - 8096:8096
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/jellyfin:/config"
        - "{{ media_folder }}:/data:ro"
      devices:
        - /dev/dri:/dev/dri
      restart: "no"
      x-systemd-requires: ['mnt-storage.mount']
    tautulli:
      x-systemd-requires: ['mnt-storage.mount']
    sonarr:
      x-systemd-requires: ['mnt-storage.mount']
    radarr:
      x-systemd-requires: ['mnt-storage.mount']
    jackett:
      x-systemd-requires: ['mnt-storage.mount']
    resilio:
      image: linuxserver/resilio-sync
      container_name: resilio
      networks:
        - apps
      ports:
        - 55555:55555
        - 55555:55555/udp
      volumes:
        - "{{ app_folder }}/resilio:/config"
        - "{{ data_folder }}:/sync"
      restart: "no"
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
      x-systemd-requires:
        - mnt-storage.mount

caddy_extras:
  users:
    - name: paul@bovbel.com
      roles: ['admin', 'share']
    - name: rebecca@bovbel.com
      roles: ['admin', 'share']
    - name: andrew@bovbel.com
      roles: ['share']
    - name: igorlitvinov@gmail.com
      roles: ['share']
    - name: garyservin@gmail.com
      roles: ['share']
    - name: ablakey@gmail.com
      roles: ['share']
    - name: eugene.tkach@gmail.com
      roles: ['share']


  endpoints:
    jellyfin:
      type: proxy
      auth: null
      path: /jellyfin
      host: jellyfin
      port: 8096
      roles: ['admin']
    resilio:
      type: proxy
      auth: oauth
      path: /gui
      host: resilio
      port: 8888
      roles: ['admin']
