---
# Useful paths
data_folder: "/storage"
app_folder: "{{ data_folder }}/app"
media_folder: "{{ data_folder }}/media"
backup_folder: "{{ data_folder }}/backup"
downloads_folder: "{{ data_folder }}/downloads"
share_folder: "{{ media_folder }}"
movies_folder: "{{ media_folder }}/movies"
tv_folder: "{{ media_folder }}/tv"
books_folder: "{{ media_folder }}/books"
audiobooks_folder: "{{ media_folder }}/audiobooks"
comics_folder: "{{ media_folder }}/comics"

zfs_pool: storage

# TODO(pbovbel) expose RDP over tailnet, and game server over WAN
aws_alias_domains:
  - tower.bovbel.com
  - homeassistant.bovbel.com

docker_extras:
  services:
    plex:
      volumes:
        - "{{ media_folder }}:/mnt/storage/share:ro"
      x-systemd-requires: ['storage.mount']
    deluge:
      environment:
        VPN_ENABLED: "yes"
        VPN_PROV: pia
        VPN_USER: "{{ pia_username }}"
        VPN_PASS: "{{ pia_password }}"
        VPN_CLIENT: wireguard
      x-systemd-requires: ['storage.mount']
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      networks:
        - apps
      ports:
        - 8096:8096
      environment:
        PUID: "{{ ansible_user_uid }}"
        PGID: "{{ ansible_user_gid }}"
        TZ: America/Toronto
      volumes:
        - "{{ app_folder }}/jellyfin:/config"
        - "{{ media_folder }}:/data:ro"
      devices:
        - /dev/dri:/dev/dri
      restart: "no"
      x-systemd-requires: ['storage.mount']
    tautulli:
      x-systemd-requires: ['storage.mount']
    sonarr:
      x-systemd-requires: ['storage.mount']
    radarr:
      x-systemd-requires: ['storage.mount']
    jackett:
      x-systemd-requires: ['storage.mount']
    enshrouded:
      image: sknnr/enshrouded-dedicated-server:proton-latest
      container_name: enshrouded
      networks:
        - apps
      environment:
        SERVER_NAME: BraveNewWorldTwo
        SERVER_PASSWORD: "{{ enshrouded_server_password }}"
        SERVER_SLOTS: 16
      ports:
        - "15636:15636/udp"
        - "15636:15636/tcp"
        - "15637:15637/udp"
        - "15637:15637/tcp"
      volumes:
        - "{{ app_folder }}/enshrouded:/home/steam/enshrouded"
      restart: "no"
      x-systemd-enabled: false
      x-systemd-requires: ['storage.mount']

upnp_forwards_extras:
  enshrouded1: {from: 15636, to: 15636, proto: tcp}
  enshrouded2: {from: 15636, to: 15636, proto: udp}
  enshrouded3: {from: 15637, to: 15637, proto: tcp}
  enshrouded4: {from: 15637, to: 15637, proto: udp}

enshrouded_server_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35623830653934623634353863353134386531613638316633353233663861376265653835343265
  3965663735653263346137393931366239363930333564650a383764383564633761666531396630
  62336134363635623765353266323732346261356437363835663662373232303264346464633964
  3637396338643166390a636633613930386338623335616635393636366666356338633530626364
  3563

caddy_extras:
  users:
    - email: paul@bovbel.com
      roles: ['admin', 'share']
    - email: rebecca@bovbel.com
      roles: ['admin', 'share']
    - email: andrew@bovbel.com
      roles: ['share']
    - email: igorlitvinov@gmail.com
      roles: ['share']
    - email: eugene.tkach@gmail.com
      roles: ['share']


  endpoints:
    jellyfin:
      type: proxy
      auth: null
      path: /jellyfin
      host: jellyfin
      port: 8096
      role: admin
