---
- name: determine uid
  command: "id -u {{ ansible_user }}"
  register: uid

- name: deterine gid
  command: "id -g {{ ansible_user }}"
  register: gid

- name: bind uid and gid to variables
  set_fact:
    uid: "{{ uid.stdout }}"
    gid: "{{ gid.stdout }}"

- name: apt install pip
  apt:
    pkg: python-pip
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: install docker_service dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-compose
  become: true

- name: build media-server docker-compose template
  template:
    src: docker_compose.yaml.j2
    dest: /tmp/docker-compose.yaml

- name: deploy media-server docker project
  docker_service:
    project_name: media-server
    project_src: /tmp
  become: true
