---
- name: add certbot repo
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
    update_cache: true
  become: true

- name: install cerbot package
  apt:
    name: certbot
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: initialize ssl certificates
  block:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
      become: true
      register: nginx_stopped

    - name: get certificates
      command: "/usr/bin/certbot certonly --standalone -m {{ ansible_email }} -d {{ public_hosts|join(',') }} --agree-tos"
      become: true
      args:
        creates: "{{ ssl_certificate }}"
  always:
    - name: start nginx
      service:
        name: nginx
        state: started
      become: true
      when: nginx_stopped.changed

- name: install certbot auto renewal service
  template:
    src: certbot.service.j2
    dest: /etc/systemd/system/certbot.service
  become: true

- name: install certbot auto renewal timer
  copy:
    src: certbot.timer
    dest: /etc/systemd/system/certbot.timer
  become: true

- name: make sure certbot timer is running
  systemd:
    name: certbot.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true
