---
- name: install samba
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  with_items:
    - samba

- name: configure samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: true
  notify: restart samba

- name: creating samba user passwords
  shell: |
    (echo {{ samba_password }}; echo {{ samba_password }}) | smbpasswd -s -a {{ ansible_user }}
  args:
    executable: /bin/bash
  become: true
  notify: restart samba
