---
- name: install aws ddns script dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  with_items:
    - dnsutils
    - awscli

- name: install aws ddns script
  get_url:
    # url: https://github.com/mthssdrbrg/ddns-route53/raw/master/ddns-route53
    url: https://raw.githubusercontent.com/paulbovbel/ddns-route53/patch-1/ddns-route53
    dest: /usr/local/bin/ddns-route53
    mode: 0755
  become: true

- name: configure aws credentials
  copy:
    src: vault/aws_credentials
    dest: /root/.aws/credentials
    mode: 0600
  become: true

- name: install aws ddns service
  template:
    src: aws-ddns@.service.j2
    dest: /etc/systemd/system/aws-ddns@.service
  become: true

- name: install aws ddns timer
  copy:
    src: aws-ddns@.timer
    dest: /etc/systemd/system/aws-ddns@.timer
  become: true

- name: enable aws ddns timers
  systemd:
    name: "aws-ddns@{{ item }}.timer"
    state: started
    enabled: true
    daemon_reload: true
  become: true
  with_items: "{{ aws_ddns_hosted_records }}"
