---
- name: enable flatpak update
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    daemon_reload: true
  become: true
  with_items:
    - flatpak-update.timer
    - flatpak-update.service
