---
- name: add tailscale apt key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg
    keyring: /etc/apt/trusted.gpg.d/tailscale.gpg
    state: present
  become: true

- name: add tailscale apt repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  become: true

- name: install tailscale agent
  apt:
    name:
      - jq
      - tailscale
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: allow caddy access to tailscale agent
  lineinfile:
    dest: /etc/default/tailscaled
    regexp: '^TS_PERMIT_CERT_UID=.*$'
    line: 'TS_PERMIT_CERT_UID=caddy'
  become: true
  notify:
    - restart tailscale

- name: start tailscale
  systemd:
    name: tailscaled
    state: started
    enabled: true
  become: true

- name: authorize tailscale
  block:
  - name: authorize machine
    shell: "tailscale up --authkey '{{ tailscale_oauth_secret }}?ephemeral=false' --advertise-tags tag:{{ tailscale_tag }} {{ '--advertise-exit-node' if tailscale_exit_node }}"
    become: true

  - name: re-gather tailscale facts
    setup:
  when: tailscale is not defined or tailscale.BackendState != "Running" or tailscale.CurrentTailnet.Name != tailscale_tailnet
