---
- name: install openssh-server
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  with_items:
    - openssh-server
    - htop
    - iotop

- name: configure hostname
  copy:
    content: |
      127.0.0.1	localhost
      127.0.1.1	{{ inventory_hostname }} {{ ansible_hostname }}

      ::1     localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
    dest: /etc/hosts
  become: true

- name: set authorized key took from file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  register: add_identity_key

- name: Disable empty password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  become: true
  notify: restart sshd

- name: Disable remote root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  become: true
  notify: restart sshd

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: add_identity_key|success and not add_identity_key|skipped
  become: true
  notify: restart sshd

- name: Enable PAM
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    line: "UsePAM yes"
  become: true
  notify: restart sshd
