---
- name: install cockpit packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
    default_release: xenial-backports
  become: true
  with_items:
    - cockpit-bridge
    - cockpit-dashboard
    - cockpit-docker
    - cockpit-packagekit
    - cockpit-pcp
    - cockpit-storaged
    - cockpit-system
    - cockpit-ws

- name: configure cockpit
  template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
  become: true
  notify: restart cockpit

- name: make sure cockpit is running
  service:
    name: cockpit
    state: started
    enabled: true
  become: true
