---
- name: install nfs client
  apt:
    pkg: nfs-common
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure rpcbind is running
  service:
    name: rpcbind
    state: started
    enabled: true
  become: true

- name: Ensure directory exists
  file:
    path: "{{ item.mount }}"
    state: directory
  become: true
  with_items:
    - "{{ nfs_mounts }}"

- name: configure /etc/fstab on clients
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.url }}"
    fstype: nfs
    opts: noauto,nofail,x-systemd.automount,x-systemd.requires=network-online.target,x-systemd.device-timeout=10,rsize=131072,wsize=131072,noatime,nodiratime
    state: mounted
  become: true
  with_items:
    - "{{ nfs_mounts }}"
