---
- name: configure podman registry
  copy:
    content: |
      [registries.search]
      registries = ['docker.io']
    dest: /etc/containers/registries.conf
  become: true

- name: install python3 venv and pip
  apt:
    name:
      - python3-pip
      - python3-venv
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: remove virtualenv folder for podman-compose
  file:
    path: "{{ virtualenv_path }}/podman-compose"
    state: absent
  become: true

- name: install podman-compose
  pip:
    name:
      - podman-compose
    state: latest
    virtualenv: "{{ virtualenv_path }}/podman-compose"
    virtualenv_command: /usr/bin/python3 -m venv
  become: true

- name: Create symbolic link to podman-compose
  file:
    src: "{{ virtualenv_path }}/podman-compose/bin/podman-compose"
    dest: "/usr/local/bin/podman-compose"
    state: link
    force: true
  become: true

- name: determine uid
  command: "id -u {{ ansible_user }}"
  register: uid
  tags: containers

- name: determine gid
  command: "id -g {{ ansible_user }}"
  register: gid
  tags: containers

- name: bind uid and gid to variables
  set_fact:
    uid: "{{ uid.stdout }}"
    gid: "{{ gid.stdout }}"
  tags: containers

- name: increase number of watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
    state: present
  become: true

- name: configure container defaults
  set_fact:
    containers: "{{ containers | combine(container_defaults, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure containers
  tags: containers
