docker:
  services:
    aws_ddns_a:
      container_name: aws_ddns_a
      image: sjmayotte/route53-dynamic-dns:latest
      networks:
        - apps
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_REGION: us-east-1
        ROUTE53_HOSTED_ZONE_ID: "{{ aws_ddns_hosted_zone }}"
        ROUTE53_TYPE: A
        ROUTE53_TTL: "300"
        UPDATE_FREQUENCY: "60000"
        SEND_EMAIL_SES: "true"
        SES_FROM_ADDRESS: "{{ ansible_email }}"
        SES_TO_ADDRESS: "{{ ansible_email }}"
        ROUTE53_DOMAIN: "{{ inventory_hostname }}"
