---
docker_sync:
  services:
    syncthing:
      image: linuxserver/syncthing
      container_name: syncthing
      networks:
        - apps
      ports:
        - 22000:22000/tcp
        - 22000:22000/udp
        - 21027:21027/udp
      volumes:
        - "{{ app_folder }}/syncthing:/config"
        - "{{ data_folder }}:/sync"
      restart: "no"
      environment:
        PUID: "{{ uid }}"
        PGID: "{{ gid }}"
        TZ: America/Toronto
      x-systemd-requires:
        - storage.mount

caddy_sync:
  endpoints:
    syncthing:
      type: proxy
      auth: oauth
      path: /syncthing
      host: syncthing
      port: 8384
      role: admin
      strip_prefix: true

upnp_forwards_sync:
  syncthing1: {from: 22000, to: 22000, proto: tcp}
  syncthing2: {from: 22000, to: 22000, proto: udp}
  syncthing3: {from: 21027, to: 21027, proto: udp}
