---
# pipewire works much better for bluetooth headphones, not default in focal
- name: add pipewire ppa
  apt_repository:
    repo: ppa:pipewire-debian/pipewire-upstream
  become: true

- name: install pipewire and bluetooth packages
  apt:
    name:
      - gstreamer1.0-pipewire
      - libspa-0.2-bluetooth
      - libspa-0.2-jack
      - pipewire
      - pipewire-audio-client-libraries
      - libical-dev
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: symlink pipewire configs
  file:
    src: /usr/share/pipewire
    dest: /etc/pipewire
    state: link
  become: true

- name: disable pulseaudio
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    scope: user
    daemon_reload: true
  loop:
    - pulseaudio.socket
    - pulseaudio.service

- name: enable pipewire
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  loop:
    - pipewire.socket
    - pipewire.service
    - pipewire-pulse.socket
    - pipewire-pulse.service
    - pipewire-media-session.service

- name: get bluetoothd version
  shell: |
    /usr/local/libexec/bluetooth/bluetoothd --version || echo None
  register: bluetoothd_version

- name: install bluetoothd from source
  when: bluez_version != bluetoothd_version.stdout
  block:
  - name: temporary bluez directory
    tempfile:
      state: directory
    register: bluez_directory

  - name: download bluez
    unarchive:
      src: "http://www.kernel.org/pub/linux/bluetooth/bluez-{{ bluez_version }}.tar.xz"
      dest: "{{ bluez_directory.path }}"
      remote_src: yes

  - name: install bluez
    shell: |
      cd {{ bluez_directory.path }}/bluez-{{ bluez_version }} &&
      ./configure &&
      make &&
      sudo make install
    become: true

- name: create service override dir
  file:
    path: /etc/systemd/system/bluetooth.service.d/
    state: directory
  become: true

- name: override service
  copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/libexec/bluetooth/bluetoothd --experimental
    dest: /etc/systemd/system/bluetooth.service.d/override.conf
  become: true
