---
docker_compose:
  version: '3.5'
  networks:
    media:
      name: media
  services:
    smtp:
      container_name: smtp
      image: namshi/smtp
      networks:
        - media
      environment:
        - "RELAY_NETWORKS=:10.0.0.0/8:172.16.0.0/12:192.168.0.0/16"
        - "GMAIL_USER={{ ansible_email }}"
        - "GMAIL_PASSWORD={{ gmail_access_key }}"
    caddy:
      build:
        args:
          plugins: login,jwt
        context: github.com/abiosoft/caddy-docker.git
      container_name: caddy
      networks:
        - media
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
      volumes:
        - /etc/docker/Caddyfile:/etc/Caddyfile:ro
        - "{{ appdata_folder }}/caddy:/root/.caddy"
        - "{{ media_folder }}:/srv/share:ro"
        - "{{ appdata_folder }}/caddy/log:/log"
    plex:
      image: plexinc/pms-docker:plexpass
      container_name: plex
      network_mode: host
      volumes:
        - "{{ appdata_folder }}/plex:/config"
        - "{{ media_folder }}:/mnt/storage/share:ro"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
      restart: unless-stopped
    emby:
      image: emby/embyserver:latest
      container_name: emby
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/emby:/config"
        - "{{ media_folder }}:/media:ro"
      environment:
        - "UID={{ uid }}"
        - "GID={{ gid }}"
      ports:
        - 8096:8096
      restart: unless-stopped
    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      networks:
        - media
      depends_on:
        - plex
      volumes:
        - "{{ appdata_folder }}/tautulli:/config"
        - "{{ appdata_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
        - media
      depends_on:
        - jackett
      volumes:
        - "{{ appdata_folder }}/sonarr:/config"
        - "{{ backup_folder }}/apps/sonarr:/config/Backups"
        - "{{ media_folder }}/tv:/tv"
        - "{{ download_folder }}:/downloads"
        - "/etc/localtime:/etc/localtime:ro"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
        - media
      depends_on:
        - jackett
      volumes:
        - "{{ appdata_folder }}/radarr:/config"
        - "{{ backup_folder }}/apps/radarr:/config/Backups"
        - "{{ media_folder }}/movies:/movies"
        - "{{ download_folder }}:/downloads"
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/jackett:/config"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    unifi:
      image: linuxserver/unifi-controller
      container_name: unifi
      network_mode: host
      volumes:
        - "{{ appdata_folder }}/unifi:/config"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    transmission:
      container_name: transmission
      image: linuxserver/transmission:latest
      networks:
        - media
      ports:
        - 51413:51413
        - 51413:51413/udp
      restart: unless-stopped
      volumes:
        - "{{ appdata_folder }}/transmission:/config"
        - "{{ download_folder }}:/downloads"
      environment:
        - PUID=1000
        - PGID=1000
    resilio:
      image: linuxserver/resilio-sync
      container_name: resilio
      networks:
        - media
      ports:
        - 55555:55555
        - 55555:55555/udp
      volumes:
        - "{{ appdata_folder }}/resilio:/config"
        - "{{ data_folder }}:/sync"
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
    watchtower:
      image: v2tec/watchtower
      container_name: watchtower
      networks:
        - media
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
