---
docker_compose:
  version: '3.5'
  networks:
    media:
      name: media
  services:
    smtp:
      container_name: smtp
      image: namshi/smtp
      networks:
        - media
      environment:
        - "RELAY_NETWORKS=:10.0.0.0/8:172.16.0.0/12:192.168.0.0/16"
        - "GMAIL_USER={{ ansible_email }}"
        - "GMAIL_PASSWORD={{ gmail_access_key }}"
    caddy:
      build:
        args:
          plugins: login,jwt
        context: github.com/abiosoft/caddy-docker.git
      container_name: caddy
      networks:
        - media
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
      volumes:
        - /etc/docker/Caddyfile:/etc/Caddyfile:ro
        - "{{ appdata_folder }}/caddy:/root/.caddy"
        - "{{ media_folder }}:/srv/share:ro"
        - "{{ appdata_folder }}/caddy/log:/log"
    plex:
      image: plexinc/pms-docker:plexpass
      container_name: plex
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/plex:/config"
        - "{{ media_folder }}:/mnt/storage/share:ro"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
      ports:
        - 32400:32400
      restart: unless-stopped
    emby:
      image: emby/embyserver:latest
      container_name: emby
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/emby:/config"
        - "{{ media_folder }}:/media:ro"
      environment:
        - "UID={{ uid }}"
        - "GID={{ gid }}"
      restart: unless-stopped
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      volumes:
        - "{{ appdata_folder }}/ombi:/config"
        - "{{ media_folder }}:/mnt/storage/share"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      networks:
        - media
      depends_on:
        - plex
      volumes:
        - "{{ appdata_folder }}/tautulli:/config"
        - "{{ appdata_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      links:
        - plex
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
        - media
      depends_on:
        - jackett
      volumes:
        - "{{ appdata_folder }}/sonarr:/config"
        - "{{ backup_folder }}/apps/sonarr:/config/Backups"
        - "{{ media_folder }}/tv:/tv"
        - "{{ download_folder }}:/downloads"
        - "/etc/localtime:/etc/localtime:ro"
      links:
        - jackett
        - deluge
        - plex
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
        - media
      depends_on:
        - jackett
      volumes:
        - "{{ appdata_folder }}/radarr:/config"
        - "{{ backup_folder }}/apps/radarr:/config/Backups"
        - "{{ media_folder }}/movies:/movies"
        - "{{ download_folder }}:/downloads"
        - /etc/localtime:/etc/localtime:ro
      links:
        - jackett
        - deluge
        - plex
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/jackett:/config"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    unifi:
      image: linuxserver/unifi
      container_name: unifi
      networks:
        - media
      volumes:
        - "{{ appdata_folder }}/unifi:/config"
      ports:
        - 3478:3478/udp
        - 10001:10001/udp
        - 8080:8080
        - 8081:8081
        - 8443:8443
        - 8843:8843
        - 8880:8880
        - 6789:6789
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    deluge:
      image: linuxserver/deluge
      container_name: deluge
      network_mode: host
      # ports:
      #   - 58846:58846
      #   - 58946:58946
      #   - 15000:15000
      volumes:
        - "{{ appdata_folder }}/deluge:/config"
        - "{{ download_folder }}:/downloads"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
    resilio:
      image: linuxserver/resilio-sync
      container_name: resilio
      networks:
        - media
      ports:
        - 55555:55555
      volumes:
        - "{{ appdata_folder }}/resilio:/config"
        - "{{ data_folder }}:/sync"
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
    watchtower:
      image: v2tec/watchtower
      container_name: watchtower
      networks:
        - media
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
