---
- name: configure ddns services
  set_fact:
    containers: "{{ containers | combine(container_aws_ddns, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure containers
  tags: containers

- name: install boto3
  apt:
    name: python3-boto3
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: "alias against {{ inventory_hostname }}"
  route53:
    state: present
    zone: bovbel.com
    record: "{{ item }}"
    type: "A"
    value: "{{ inventory_hostname }}"
    alias: true
    alias_hosted_zone_id: "{{ aws_ddns_hosted_zone }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    overwrite: true
  with_items: "{{ aws_alias_domains }}"
  tags: ddns
