---
- name: restart cockpit
  service:
    name: cockpit
    state: restarted
    enabled: true
  become: true

- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: true
  become: true

- name: restart postfix
  service:
    name: postfix
    state: restarted
    enabled: true
  become: true

- name: generate postfix db
  command: |
    /usr/sbin/postmap hash:/etc/postfix/sasl_passwd
  args:
    creates: /etc/postfix/sasl_passwd.db
  become: true

- name: update apt cache
  apt:
    update_cache: true
