---
- name: restart cockpit
  service:
    name: cockpit
    state: restarted
  become: true

- name: restart postfix
  service:
    name: postfix
    state: restarted
  become: true

- name: build postfix database
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd
  become: true
  notify: restart postfix
