---
- name: install docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
  become: true

- name: install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    # - cockpit-docker  # removed in 20.04
      - python3-docker
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: install python3 venv and pip
  apt:
    name:
      - python3-pip
      - python3-venv
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: configure docker group
  group:
    name: docker
    state: present
  become: true

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
  notify: restart docker

- name: determine uid
  command: "id -u {{ ansible_user }}"
  register: uid
  tags: docker

- name: determine gid
  command: "id -g {{ ansible_user }}"
  register: gid
  tags: docker

- name: bind uid and gid to variables
  set_fact:
    uid: "{{ uid.stdout }}"
    gid: "{{ gid.stdout }}"
  tags: docker

- name: increase number of watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
    state: present
  become: true

- name: configure docker defaults
  set_fact:
    docker: "{{ docker | combine(docker_defaults, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure docker
  tags: docker
