---
- name: install openssh-server
  apt:
    name:
      - openssh-server
      - fail2ban
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: configure hosts file
  copy:
    content: |
      127.0.0.1 localhost
      127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }}

      ::1 localhost6.localdomain6 localhost6
      fe00::0 ip6-localnet
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts
    dest: /etc/hosts
  become: true

- name: set authorized key from github
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: https://github.com/paulbovbel.keys

- name: harden sshd
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '^#?\s*{{ item.key }}.*'
    value: "{{ item.key }} {{ item.value }}"
    validate: "sshd -t -f %s"
  loop: "{{ sshd_config | dict2items }}"
  become: true
  notify: reload sshd
