---
- name: install zfs
  apt:
    name:
      - zfs-dkms
      - zfsutils-linux
      - zfs-auto-snapshot
      - zfs-zed
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: zfs_pool is defined

- name: import pool if necessary
  shell: |
    zpool status {{ zfs_pool }} || zpool import {{ zfs_pool }}
  become: true
  when: zfs_pool is defined

- name: configure zed
  lineinfile:
    dest: /etc/zfs/zed.d/zed.rc
    regexp: "ZED_EMAIL_ADDR"
    line: "ZED_EMAIL_ADDR='{{ ansible_email }}'"
  become: true
  notify: restart zed

- name: install nfs client
  apt:
    pkg: nfs-common
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: nfs_mounts is defined

- name: Ensure directory exists
  file:
    path: "{{ item.mount }}"
    state: directory
  become: true
  with_items:
    - "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: configure nfs mounts
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.url }}"
    fstype: nfs
    opts: defaults,noatime,nodiratime,_netdev,auto,x-systemd.requires=network-online.target,x-systemd.before=docker.service
    state: mounted
  become: true
  with_items:
    - "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: install open-iscsi
  apt:
    pkg: open-iscsi
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: iscsi_host is defined

- name: start open-iscsi
  systemd:
    name: iscsid.service
    state: started
    enabled: true
  become: true
  when: iscsi_host is defined

- name: discover iscsi
  open_iscsi:
    portal: "{{ iscsi_host }}"
    discover: true
    login: true
    auto_node_startup: true
    show_nodes: true
  become: true
  when: iscsi_host is defined
  register: iscsi

- name: configure iscsi mount
  mount:
    name: "{{ app_folder }}"
    src: "/dev/disk/by-path/ip-{{ iscsi_host }}:3260-iscsi-{{ iscsi.nodes[0] }}-lun-0-part1"
    fstype: ext4
    opts: defaults,noatime,nodiratime,_netdev,auto,x-systemd.requires=network-online.target,x-systemd.before=docker.service
    state: mounted
  become: true
  when: iscsi_host is defined
