---
- name: restart cockpit
  service:
    name: cockpit
    state: restarted
    enabled: true
  become: true

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: true
  become: true

- name: restart caddy
  shell:
    docker restart caddy
  become: true

- name: update apt cache
  apt:
    update_cache: true

- name: update-grub
  shell: update-grub
  become: true
