aws_ddns: false

container_aws_ddns:
  services:
    ddns-route53:
      container_name: ddns-route53
      image: crazymax/ddns-route53:latest
      networks:
        - apps
      environment:
        TZ: America/Toronto
        SCHEDULE: "*/30 * * * *"
        LOG_LEVEL: info
        LOG_JSON: "false"
        DDNSR53_CREDENTIALS_ACCESSKEYID: "{{ aws_access_key_id }}"
        DDNSR53_CREDENTIALS_SECRETACCESSKEY: "{{ aws_secret_access_key }}"
        DDNSR53_ROUTE53_HOSTEDZONEID: "{{ aws_ddns_hosted_zone }}"
        DDNSR53_ROUTE53_RECORDSSET_0_NAME: "{{ inventory_hostname }}"
        DDNSR53_ROUTE53_RECORDSSET_0_TYPE: A
        DDNSR53_ROUTE53_RECORDSSET_0_TTL: 300
      restart: always
