---
- name: install zfs
  apt:
    name:
      - zfsutils-linux
      - zfs-auto-snapshot
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: import pool if necessary
  shell: |
    zpool import storage || true
  become: true

- name: populate kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel_options | join(" ") }}"'
  become: true
  notify:
    - update-grub
