---
- hosts: server
  roles:
    - base
    - aws-ddns
    - cockpit
    - caddy
    - media-server

- hosts:
    - server
  tasks:
    - name: update all remaining packages
      apt:
        upgrade: dist
        force: true
      become: true

    - name: autoremove apt
      apt:
        autoremove: true
        purge: true
      become: true

    - name: autoclean apt
      apt:
        autoclean: true
      become: true
