---
- hosts: app_server
  roles:
    - base
    - aws_ddns
    - cockpit
    - caddy

- hosts: media_server
  roles:
    - base
    - aws_ddns
    - cockpit
    - caddy
    - media-server
    # - nextcloud

- hosts:
    - app_server
    - media_server
  tasks:
    - name: update all remaining packages
      apt:
        upgrade: dist
        force: true
      become: true
    - name: clean apt
      shell: apt-get autoremove --purge -y && apt-get clean
      become: true
