---
- hosts: app_server
  roles:
    - base
    - cockpit

- hosts: media_server
  roles:
    - base
    - cockpit
    - media-server

- hosts:
    - app_server
    - media_server
  roles:
    - role: stuvusit.smartd
      become: true
      vars:
        smartd_default_mail_recipients: ["{{ ansible_email }}"]
        smartd_default_mail_frequency: test
