---
- hosts: app_server
  roles:
    - base
    - cockpit
    - caddy

- hosts: media_server
  roles:
    - base
    - cockpit
    - media-server

- hosts:
    - app_server
    - media_server
  roles:
    - role: stuvusit.smartd
      become: true
      vars:
        smartd_default_mail_recipients: ["{{ ansible_email }}"]
  tasks:
    - name: update all remaining packages
      apt:
        upgrade: dist
        force: true
      become: true

    - name: clean apt
      shell: apt-get autoremove --purge -y && apt-get clean
      become: true
