---
- hosts: media_server
  roles:
    - base
    - aws-ddns
    - cockpit
    - caddy
    - sync
    - upnp
    - media-server
    - minecraft

- hosts: home_server
  roles:
    - base
    - aws-ddns
    - cockpit
    - caddy
    - homeassistant
    - sync
    - upnp
    - miyoo-backup

- hosts:
    - all
  tasks:
    - name: update all remaining packages
      apt:
        upgrade: dist
        force: true
      become: true

    - name: autoremove apt
      apt:
        autoremove: true
        purge: true
      become: true

    - name: autoclean apt
      apt:
        autoclean: true
      become: true
