name: ansible lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: write vault_pass to file
      run: echo $VAULT_PASS >> vault_pass.txt
      shell: bash
      env:
        VAULT_PASS : ${{ secrets.VAULT_PASS }}

    - name: lint ansible playbooks
      uses: ansible-community/ansible-lint-action@v6.0.2
      with:
        args: "playbooks/*"
