name: ansible lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: write vault_pass to file
      run: echo $VAULT_PASS >> vault_pass.txt
      shell: bash
      env:
        VAULT_PASS : ${{ secrets.VAULT_PASS }}
    - name: lint ansible playbooks
      uses: ansible/ansible-lint-action@f05dc373850a80f1da58eae655e47b85502cacbf
      with:
        targets: "playbooks/*"
        override-deps: |
          ansible>2.10
