name: ansible deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - media.bovbel.com
          - home.bovbel.com


    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: unnecessary

    - name: Write secrets
      shell: bash
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
      run: echo $VAULT_PASS >> vault_pass.txt

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}

    - name: Install pip
      run: |
        python3 -m venv venv
        venv/bin/pip install -r requirements.txt

    - name: Cache ansible
      uses: actions/cache@v1
      with:
        path: |
          ~/.ansible/collections
          roles/stuvusit.smartd
        key: ${{ hashFiles('requirements.yaml') }}

    - name: Install ansible galaxy
      shell: bash
      env:
        VAULT_PASS : ${{ secrets.VAULT_PASS }}
      run: |
        venv/bin/ansible-galaxy install -r requirements.yaml

    - name: Run ansible
      shell: bash
      env:
        TARGET : ${{ matrix.target }}
      run: |
        ssh-keyscan -H $TARGET >> ~/.ssh/known_hosts &&
        venv/bin/ansible-playbook -i inventory/bovbel --limit $TARGET playbooks/lab.yaml
